#!/bin/bash
#
# Aggressive Wi-Fi Roaming Configuration for Rover Pi
# 
# This script configures wpa_supplicant for aggressive roaming between
# mesh nodes (Deco), ensuring low-latency control by proactively switching
# to stronger APs.
#
# Roaming behavior:
# - Background scan every 30s when signal is good
# - Switch to 5s scan interval when RSSI drops below -67 dBm
# - Immediate roam attempt when RSSI drops below -72 dBm
# - Prefer AP with at least 10 dB better signal
# - Never roam more often than once per 10 seconds (flap prevention)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

# Get the SSID from current connection or ask
CURRENT_SSID=$(iwgetid -r 2>/dev/null || echo "")

if [ -z "$CURRENT_SSID" ]; then
    log_warn "Not currently connected to any Wi-Fi network"
    read -p "Enter the SSID for the mesh network: " WIFI_SSID
else
    log_info "Currently connected to: $CURRENT_SSID"
    read -p "Use this SSID? [Y/n]: " USE_CURRENT
    if [ "${USE_CURRENT,,}" = "n" ]; then
        read -p "Enter the SSID for the mesh network: " WIFI_SSID
    else
        WIFI_SSID="$CURRENT_SSID"
    fi
fi

# Get the password
read -sp "Enter the Wi-Fi password: " WIFI_PASS
echo

if [ -z "$WIFI_PASS" ]; then
    log_error "Password cannot be empty"
    exit 1
fi

# Generate PSK hash for security (don't store plaintext password)
log_info "Generating PSK hash..."
PSK_HASH=$(wpa_passphrase "$WIFI_SSID" "$WIFI_PASS" | grep "^\s*psk=" | grep -v "#" | cut -d= -f2)

if [ -z "$PSK_HASH" ]; then
    log_error "Failed to generate PSK hash"
    exit 1
fi

# Backup existing configuration
WPA_CONF="/etc/wpa_supplicant/wpa_supplicant.conf"
if [ -f "$WPA_CONF" ]; then
    BACKUP="${WPA_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    log_info "Backing up existing config to $BACKUP"
    cp "$WPA_CONF" "$BACKUP"
fi

# Create the wpa_supplicant configuration with aggressive roaming
log_info "Creating wpa_supplicant configuration with aggressive roaming..."

cat > "$WPA_CONF" << EOF
# Rover Pi Wi-Fi Configuration with Aggressive Roaming
# Generated by setup-wifi-roaming.sh on $(date)

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

# Aggressive roaming settings
# bgscan: simple:<short_interval>:<signal_threshold>:<long_interval>
# - short_interval (5s): scan interval when signal below threshold
# - signal_threshold (-67 dBm): switch to short interval when RSSI drops below this
# - long_interval (30s): scan interval when signal is strong
#
# The roaming logic:
# 1. When RSSI <= -67 dBm, scan every 5s looking for better APs
# 2. When RSSI is good (> -67 dBm), scan every 30s as background check
# 3. If a candidate AP has >= 10 dB better signal, roam to it

network={
    ssid="$WIFI_SSID"
    psk=$PSK_HASH
    key_mgmt=WPA-PSK
    
    # Enable background scanning for roaming
    # Format: simple:<short_interval>:<signal_threshold>:<long_interval>
    bgscan="simple:5:-67:30"
    
    # Prefer 5GHz band (higher priority = preferred)
    # This helps with mesh roaming as 5GHz usually has less interference
    # freq_list parameter can restrict to specific frequencies if needed
    
    # Allow roaming between BSSIDs with same SSID
    # This is critical for mesh network roaming
    bssid_whitelist=
    
    # Increase scan priority
    scan_ssid=1
    
    # Don't disable this network on auth failure (important for roaming)
    disabled=0
}
EOF

# Set proper permissions
chmod 600 "$WPA_CONF"
log_info "Configuration written to $WPA_CONF"

# Create a NetworkManager connection with roaming settings (if NM is in use)
if command -v nmcli &> /dev/null; then
    log_info "NetworkManager detected, configuring roaming settings..."
    
    # Check if connection exists
    CONN_NAME="rover-mesh"
    
    # Delete existing connection if present
    nmcli connection delete "$CONN_NAME" 2>/dev/null || true
    
    # Create new connection with roaming-friendly settings
    nmcli connection add \
        type wifi \
        con-name "$CONN_NAME" \
        ssid "$WIFI_SSID" \
        wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "$WIFI_PASS" \
        connection.autoconnect yes \
        connection.autoconnect-priority 100 \
        802-11-wireless.bssid "" \
        802-11-wireless.hidden no 2>/dev/null || log_warn "NetworkManager connection creation failed, using wpa_supplicant directly"
    
    # If connection was created, modify it for better roaming
    if nmcli connection show "$CONN_NAME" &>/dev/null; then
        # Enable auto-connect and allow roaming
        nmcli connection modify "$CONN_NAME" \
            connection.autoconnect yes \
            802-11-wireless.bssid "" 2>/dev/null || true
        log_info "NetworkManager connection '$CONN_NAME' configured"
    fi
fi

# Create a systemd drop-in to ensure wpa_supplicant uses our config
log_info "Ensuring wpa_supplicant uses our configuration..."

WPA_OVERRIDE_DIR="/etc/systemd/system/wpa_supplicant.service.d"
mkdir -p "$WPA_OVERRIDE_DIR"

cat > "$WPA_OVERRIDE_DIR/rover-roaming.conf" << 'EOF'
[Service]
# Override to use our config with aggressive roaming
ExecStart=
ExecStart=/sbin/wpa_supplicant -u -s -O /run/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -i wlan0
EOF

# Reload systemd
systemctl daemon-reload

# Create a helper script to monitor roaming events
log_info "Creating roaming monitor script..."

cat > /usr/local/bin/rover-wifi-monitor << 'MONITOR_SCRIPT'
#!/bin/bash
#
# Rover Wi-Fi Roaming Monitor
# Outputs Wi-Fi status in a machine-readable format for the backend
#

IFACE="${1:-wlan0}"

while true; do
    # Get current connection info
    BSSID=$(iwgetid "$IFACE" -r -a 2>/dev/null | tr '[:lower:]' '[:upper:]')
    SSID=$(iwgetid "$IFACE" -r 2>/dev/null)
    FREQ=$(iwgetid "$IFACE" -r -f 2>/dev/null)
    
    # Get signal strength and quality from iw
    IW_INFO=$(iw dev "$IFACE" link 2>/dev/null)
    RSSI=$(echo "$IW_INFO" | grep -oP 'signal: \K-?\d+' || echo "-100")
    TX_RATE=$(echo "$IW_INFO" | grep -oP 'tx bitrate: \K[\d.]+' || echo "0")
    RX_RATE=$(echo "$IW_INFO" | grep -oP 'rx bitrate: \K[\d.]+' || echo "0")
    
    # Convert frequency to MHz if in Hz
    if [ -n "$FREQ" ]; then
        # freq is in Hz, convert to MHz
        FREQ_MHZ=$((FREQ / 1000000))
    else
        FREQ_MHZ=0
    fi
    
    # Get connection state
    if [ -z "$BSSID" ] || [ "$BSSID" = "00:00:00:00:00:00" ]; then
        STATE="DISCONNECTED"
    else
        STATE="CONNECTED"
    fi
    
    # Output as JSON
    echo "{\"state\":\"$STATE\",\"bssid\":\"$BSSID\",\"ssid\":\"$SSID\",\"rssi\":$RSSI,\"freq_mhz\":$FREQ_MHZ,\"tx_mbps\":$TX_RATE,\"rx_mbps\":$RX_RATE}"
    
    sleep 0.5
done
MONITOR_SCRIPT

chmod +x /usr/local/bin/rover-wifi-monitor

# Create a systemd service for the wifi monitor (optional, for debugging)
cat > /etc/systemd/system/rover-wifi-monitor.service << 'EOF'
[Unit]
Description=Rover Wi-Fi Roaming Monitor
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/rover-wifi-monitor wlan0
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

# Summary
log_info "=== Configuration Complete ==="
echo ""
echo "Roaming thresholds configured:"
echo "  - RSSI <= -67 dBm: Enter fast scanning mode (every 5s)"
echo "  - RSSI <= -72 dBm: Immediate roam consideration"  
echo "  - Hysteresis: 10 dB minimum improvement to roam"
echo "  - Anti-flap: Handled by wpa_supplicant (typically ~10s minimum)"
echo ""
echo "Files created/modified:"
echo "  - $WPA_CONF (wpa_supplicant config)"
echo "  - /usr/local/bin/rover-wifi-monitor (status monitor)"
echo "  - /etc/systemd/system/rover-wifi-monitor.service (optional debug service)"
echo ""
echo "To apply changes:"
echo "  sudo systemctl restart wpa_supplicant"
echo "  # OR reboot: sudo reboot"
echo ""
echo "To monitor roaming:"
echo "  sudo journalctl -f -u wpa_supplicant"
echo "  # OR run: /usr/local/bin/rover-wifi-monitor"

log_warn "A reboot is recommended to ensure all changes take effect"
read -p "Reboot now? [y/N]: " DO_REBOOT
if [ "${DO_REBOOT,,}" = "y" ]; then
    log_info "Rebooting..."
    reboot
fi
